program: corruptmnist/models/train_model.py
method: bayes
metric:
  goal: minimize
  name: Loss
parameters:
  learning_rate:
    min: 0.0001
    max: 1.0
  train_batch_size:
    min: 1
    max: 100
  epochs:
    min: 4
    max: 20

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}